language: node_js
node_js:
- stable
- '6'
before_script:
  - npm install -g eslint
script: 
  - npm run lint
  - npm test
jobs:
  include:
    - stage: npm release
      node_js: stable
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_API_KEY
        on: master